version: '3.8'
services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  gateway-server:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      - eureka-server

  restaurant-service:
    build: ./microservice1
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      - gateway-server

  reservation-service:
    build: ./microservice2
    ports:
      - "8082:8082"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      - gateway-server

  reclamation-service:
    build: ./microservice5
    ports:
      - "8085:8085"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    depends_on:
      - gateway-server


