# Configuration pour le profil de développement
spring.application.name=microservice6
server.port=8086

# Désactiver l'envoi d'emails réels
app.email.enabled=true

# Configuration pour l'envoi d'emails (non utilisée en dev, mais nécessaire pour la configuration)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@gmail.com
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
