spring.application.name=microservice6


server.port=8086

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=refresh,health,info

# Configuration pour l'envoi d'emails avec Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=votre_username_mailtrap
spring.mail.password=votre_password_mailtrap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Activer l'envoi d'emails simulés
app.email.enabled=true

# Désactiver la vérification de santé du service mail
management.health.mail.enabled=false
