# Configuration pour utiliser Mailtrap (service de test d'emails)
spring.application.name=microservice6
server.port=8086

# Activer l'envoi d'emails
app.email.enabled=true

# Configuration Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=votre_username_mailtrap
spring.mail.password=votre_password_mailtrap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
