version: '3.9'

services:
  eureka-server:
    container_name: eureka-server
    image: yourdockerhubusername/eureka-server
    build: ./EurekaServer
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
    networks:
      - spring-net

  config-server:
    container_name: config-server
    image: khalilhichri/config-server
    build: ./ConfigServer
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - spring-net

  microservice4:
    container_name: microservice4
    image: khalilhichri/microservice4
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mysqldb
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/micro4?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=khalilichri@gmail.com
      - SPRING_MAIL_PASSWORD=sirs abvp iqgl niyq
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
    networks:
      - spring-net

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro4
    ports:
      - "3306:3306"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
